---
#######################
# 
# tasks file for haproxy
# 1. var_global_id 用于批量删除一次部署的所有acl+backend
# 2. 添加时不再判断是否存在
# 3. http 默认80 frontend name 为 main
# ######################
 - name: delete config file
   shell: rm -rf /etc/haproxy/conf.d/{{var_frontend_name}}-d-{{var_global_id}}*.cfg  
   when: config_ops is defined and config_ops in ( 'delete','update') 
 - name: rm use acls
   lineinfile:
     dest: "/etc/haproxy/conf.d/{{var_frontend_name}}.cfg"
     regexp: '^  acl {{var_global_id}}'
     state: absent
   #with_items: "{{var_acls}}"
   when: var_acls is defined and config_ops is defined and config_ops in ( 'delete','update')
 - name: rm use backend
   lineinfile:
     dest: "/etc/haproxy/conf.d/{{var_frontend_name}}.cfg"
     regexp: '^  use_backend {{var_frontend_name}}-{{var_global_id}}'
     state: absent
   when: config_ops is defined and config_ops in ( 'delete','update')
 - name: sync haproxy config file
   template:
     src: 02-haproxy.cfg.j2
     dest: /etc/haproxy/conf.d/{{var_frontend_name}}-d-{{var_backend_name}}.cfg
   when: config_ops is defined and config_ops in ( 'add','update')
 - name: add acl  config
   lineinfile:
     dest: "/etc/haproxy/conf.d/{{var_frontend_name}}.cfg"
     insertbefore: '^##{{var_frontend_name }} end'
     #line: "  acl {{item.name }} {{item.acl.recursive | default(false)}}"
     line: "  acl {{item.name}} {{item.operator}}  {{item.value}}"
   with_items:  "{{var_acls}}"
   when: config_ops is defined and config_ops in ( 'add','update') and var_acls is defined
 - name: add backend  config
   lineinfile:
        dest: "/etc/haproxy/conf.d/{{var_frontend_name}}.cfg"
        insertbefore: '^##{{var_frontend_name }} end'
        line: "  use_backend {{var_frontend_name}}-{{var_backend_name}}  if {{ var_acls | map(attribute='name') | join(' ') }}"
   when: var_acls is defined and config_ops is defined and config_ops== 'add'
 - name: add backend default  config
   lineinfile:
        dest: "/etc/haproxy/conf.d/{{var_frontend_name}}.cfg"
        insertbefore: '^##{{var_frontend_name }} end'
        line: "  default_backend {{var_frontend_name}}-{{var_backend_name}}"
   when: var_acls is undefined and config_ops is defined and config_ops== 'add'
 - name: restart
   shell: /bin/bash /tmp/haconfig.sh
